version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: myusername
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: ContentDistributionDb 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrations-briefing:
    build:
      context: src/BriefingService 
      dockerfile: Dockerfile.migrations
    container_name: migrations-briefing
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=ContentDistributionDb;Username=myusername;Password=mypassword
    command: ["sh", "-c", "dotnet ef database update --project /src/BriefingService/BriefingService.csproj"]

  migrations-orderlist:
    build:
      context: src/OrderListService 
      dockerfile: Dockerfile.migrations
    container_name: migrations-orderlist
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=ContentDistributionDb;Username=myusername;Password=mypassword
    command: ["sh", "-c", "dotnet ef database update --project /src/OrderListService/OrderListService.csproj"]

  webapi-briefing:
    image: briefingservice:latest
    container_name: briefing_webapi
    build:
      context: src/BriefingService 
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=ContentDistributionDb;Username=myusername;Password=mypassword
    depends_on:
      - db
    ports:
      - "5054:8080"

  webapi-orderlist:
    image: orderlistservice:latest
    container_name: orderlist_webapi
    build:
      context: src/OrderListService
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=ContentDistributionDb;Username=myusername;Password=mypassword
    depends_on:
      - db
    ports:
      - "5219:8080"

volumes:
  postgres_data:

